'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Bands', [
      {
        "name": "AC/DC",
        "history": "AC/DC es una banda de rock australiana formada en Sídney en 1973. Su música se caracteriza por un sonido de hard rock y son conocidos por canciones icónicas como 'Highway to Hell' y 'Back in Black.'",
        "mainImage": "logo-acdc.png",
        "categoryId": 1,
        "phrase": "For Those About to Rock, We Salute You",
        "dateFounded": 1973,
        "dateEnded": null,
        "totalShows": 100,
        "nextShows": "2023-01-01",
        "resume": "AC/DC es una de las bandas de rock más influyentes de la historia, conocidos por sus electrizantes actuaciones en vivo y su música atemporal.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Guns N' Roses",
        "history": "Guns N' Roses es una banda de rock estadounidense formada en Los Ángeles en 1985. Son famosos por canciones de éxito como 'Sweet Child o' Mine' y 'November Rain.'",
        "mainImage": "logo-guns.png",
        "categoryId": 1,
        "phrase": "Welcome to the Jungle",
        "dateFounded": 1985,
        "dateEnded": null,
        "totalShows": 80,
        "nextShows": "2023-01-01",
        "resume": "La música de Guns N' Roses combina el hard rock con elementos de punk y blues, convirtiéndolos en una sensación del rock 'n' roll.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Led Zeppelin",
        "history": "Led Zeppelin fue una banda de rock británica formada en Londres en 1968. Son considerados pioneros del hard rock y el heavy metal.",
        "mainImage": "logo-zepelin.png",
        "categoryId": 1,
        "phrase": "Stairway to Heaven",
        "dateFounded": 1968,
        "dateEnded": 1980,
        "totalShows": 150,
        "nextShows": "2023-01-01",
        "resume": "La música innovadora de Led Zeppelin y sus actuaciones icónicas dejaron una huella imborrable en el mundo del rock.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Muse",
        "history": "Muse es una banda de rock inglesa formada en Teignmouth en 1994. Son conocidos por su mezcla de rock, elementos electrónicos y orquestales en su música.",
        "mainImage": "logo-muse.png",
        "categoryId": 3,
        "phrase": "Uprising",
        "dateFounded": 1994,
        "dateEnded": null,
        "totalShows": 70,
        "nextShows": "2023-01-01",
        "resume": "Muse es celebrado por sus actuaciones innovadoras y llenas de energía.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Nirvana",
        "history": "Nirvana fue una banda de rock estadounidense formada en Seattle en 1987. Jugaron un papel clave en el movimiento de música grunge de los años 90.",
        "mainImage": "logo-nirvana.png",
        "categoryId": 3,
        "phrase": "Come as You Are",
        "dateFounded": 1987,
        "dateEnded": 1994,
        "totalShows": 50,
        "nextShows": "2023-01-01",
        "resume": "La música de Nirvana y el legado de Kurt Cobain continúan influyendo e inspirando a generaciones.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Pink Floyd",
        "history": "Pink Floyd es una banda de rock británica formada en Londres en 1965. Son conocidos por su rock progresivo y psicodélico.",
        "mainImage": "logo-pinkfloyd.png",
        "categoryId": 1,
        "phrase": "Wish You Were Here",
        "dateFounded": 1965,
        "dateEnded": 1995,
        "totalShows": 100,
        "nextShows": "2023-01-01",
        "resume": "Los álbumes conceptuales y los elaborados espectáculos en vivo de Pink Floyd los convirtieron en una de las bandas de rock más influyentes de la historia.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Queen",
        "history": "Queen es una banda de rock británica formada en Londres en 1970. Son conocidos por su estilo musical diverso y su icónico líder, Freddie Mercury.",
        "mainImage": "logo-queen.png",
        "categoryId": 1,
        "phrase": "Bohemian Rhapsody",
        "dateFounded": 1970,
        "dateEnded": 1991,
        "totalShows": 120,
        "nextShows": "2023-01-01",
        "resume": "La música y la puesta en escena de Queen siguen cautivando a audiencias de todo el mundo.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Rage Against the Machine",
        "history": "Rage Against the Machine es una banda de rock estadounidense formada en Los Ángeles en 1991. Su música combina rock, rap y activismo social.",
        "mainImage": "logo-ratm.jpg",
        "categoryId": 3,
        "phrase": "Killing in the Name",
        "dateFounded": 1991,
        "dateEnded": 2000,
        "totalShows": 60,
        "nextShows": "2023-01-01",
        "resume": "Las letras políticamente cargadas y la poderosa música de Rage Against the Machine impactaron a los fanáticos.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Red Hot Chili Peppers",
        "history": "Red Hot Chili Peppers es una banda de rock estadounidense formada en Los Ángeles en 1983. Son conocidos por fusionar rock, funk y punk.",
        "mainImage": "logo-rhcp.png",
        "categoryId": 4,
        "phrase": "Under the Bridge",
        "dateFounded": 1983,
        "dateEnded": null,
        "totalShows": 90,
        "nextShows": "2023-01-01",
        "resume": "Las enérgicas actuaciones y el estilo único de Red Hot Chili Peppers los han convertido en una banda querida.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "The Beatles",
        "history": "The Beatles fueron una banda de rock inglesa formada en Liverpool en 1960. Son una de las bandas más influyentes en la historia de la música.",
        "mainImage": "logo-thebeatles.png",
        "categoryId": 1,
        "phrase": "All You Need Is Love",
        "dateFounded": 1960,
        "dateEnded": 1970,
        "totalShows": 150,
        "nextShows": "2023-01-01",
        "resume": "Las canciones atemporales y el impacto cultural de The Beatles siguen resonando en audiencias de todas las edades.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Divididos",
        "history": "Divididos es una banda de rock argentino formada en 1988 en Hurlingham, Buenos Aires. La banda se originó a partir de la separación de Sumo tras la muerte de Luca Prodan.",
        "mainImage": "logo-divididos.png",
        "categoryId": 2,
        "phrase": "Sobran motivos",
        "dateFounded": 1988,
        "dateEnded": null,
        "totalShows": 120,
        "nextShows": "2023-01-01",
        "resume": "Divididos ha dejado una huella indeleble en la historia del rock argentino con su estilo único y su mezcla de rock, punk y candombe.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "La Renga",
        "history": "La Renga es una banda de rock argentino formada en 1988 en Buenos Aires. La banda es conocida por su estilo de rock y sus letras reflexivas y contestatarias.",
        "mainImage": "logo-laRenga.jpg",
        "categoryId": 2,
        "phrase": "Veneno",
        "dateFounded": 1988,
        "dateEnded": null,
        "totalShows": 100,
        "nextShows": "2023-01-01",
        "resume": "La Renga se ha destacado por sus apasionadas actuaciones en vivo y su compromiso con causas sociales.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Los Piojos",
        "history": "Los Piojos fue una banda de rock argentino formada en 1988 en El Palomar, Buenos Aires. Fueron una de las bandas más populares y exitosas de Argentina.",
        "mainImage": "logo-losPiojos.png",
        "categoryId": 2,
        "phrase": "Ando Ganas",
        "dateFounded": 1988,
        "dateEnded": 2011,
        "totalShows": 80,
        "nextShows": "2023-01-01",
        "resume": "Los Piojos dejaron una marca indeleble en la música argentina con su estilo de rock y letras poéticas.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Soda Stereo",
        "history": "Soda Stereo fue una banda de rock en español formada en 1982 en Buenos Aires, Argentina. Fueron pioneros en el rock latino y dejaron un legado duradero en la música.",
        "mainImage": "logo-sodaStereo.png",
        "categoryId": 2,
        "phrase": "De Música Ligera",
        "dateFounded": 1982,
        "dateEnded": 1997,
        "totalShows": 200,
        "nextShows": "2023-01-01",
        "resume": "Soda Stereo es considerado uno de los grupos más influyentes del rock en español, conocidos por su innovación y visión artística.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Sumo",
        "history": "Sumo fue una banda de rock argentino formada en 1981 por el cantante y líder Luca Prodan. La banda fusionó rock, reggae y punk en su música.",
        "mainImage": "logo-sumo.jpg",
        "categoryId": 2,
        "phrase": "La Rubia Tarada",
        "dateFounded": 1981,
        "dateEnded": 1987,
        "totalShows": 70,
        "nextShows": "2023-01-01",
        "resume": "Sumo dejó una profunda influencia en la escena del rock argentino con su fusión única de estilos y letras provocativas.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "Indio Solari",
        "history": "Carlos Alberto Solari, conocido como Indio Solari, es un músico argentino y exlíder de Patricio Rey y sus Redonditos de Ricota. Su carrera en solitario lo ha convertido en una figura icónica del rock argentino.",
        "mainImage": "logo-indio.png",
        "categoryId": 2,
        "phrase": "To Beef or Not to Beef",
        "dateFounded": null,
        "dateEnded": null,
        "totalShows": 50,
        "nextShows": "2023-01-01",
        "resume": "Indio Solari es reverenciado por su lírica inteligente y su impacto duradero en la música y la cultura argentina.",
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "name": "The Strokes",
        "history": "The Strokes es una banda de rock estadounidense formada en Nueva York en 1998. Son conocidos por su álbum debut, 'Is This It', que influyó en el renacimiento del garage rock en la década de 2000.",
        "mainImage": "logo-thestrokes.png",
        "categoryId": 1,
        "phrase": "Last Nite",
        "dateFounded": 1998,
        "dateEnded": null,
        "totalShows": 100,
        "nextShows": "2023-01-01",
        "resume": "The Strokes son una de las bandas más influyentes de la década de 2000, conocidos por su sonido crudo y su estilo característico.",
        "createdAt": "2023-10-19T00:00:00Z",
        "updatedAt": "2023-10-19T00:00:00Z"
      },
      {
        "name": "Arctic Monkeys",
        "history": "Arctic Monkeys es una banda británica formada en Sheffield en 2002. Han ganado reconocimiento por su estilo indie rock y éxitos como 'I Bet You Look Good On The Dancefloor' y 'Do I Wanna Know?'.",
        "mainImage": "logo-arcticmonkeys.png",
        "categoryId": 1,
        "phrase": "Do I Wanna Know?",
        "dateFounded": 2002,
        "dateEnded": null,
        "totalShows": 90,
        "nextShows": "2023-01-01",
        "resume": "Arctic Monkeys son una de las bandas más influyentes del siglo XXI, conocidos por su lírica inteligente y su evolución musical.",
        "createdAt": "2023-10-19T00:00:00Z",
        "updatedAt": "2023-10-19T00:00:00Z"
      },
      {
        "name": "Tame Impala",
        "history": "Tame Impala es el proyecto musical del músico australiano Kevin Parker, formado en Perth en 2007. La música de Tame Impala fusiona el rock psicodélico con elementos de la música electrónica.",
        "mainImage": "logo-tameimpala.png",
        "categoryId": 1,
        "phrase": "The Less I Know the Better",
        "dateFounded": 2007,
        "dateEnded": null,
        "totalShows": 80,
        "nextShows": "2023-01-01",
        "resume": "Tame Impala es conocido por su sonido psicodélico y su habilidad para crear experiencias auditivas envolventes.",
        "createdAt": "2023-10-19T00:00:00Z",
        "updatedAt": "2023-10-19T00:00:00Z"
      }

    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Bands', null, {});
  }
};