'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Albums', [
      {
        "title": "Highway to Hell",
        "discography": "Discografía1",
        "image": "acdc-album1.jpg",
        "year": 1979,
        "price": 25,
        "discount": null,
        "description": "El sexto álbum de estudio de AC/DC, 'Highway to Hell', es uno de los discos más icónicos de la banda, con canciones como 'Highway to Hell' y 'Girls Got Rhythm'.",
        "exclusive": 0,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Iron Man 2",
        "discography": "Discografía1",
        "image": "acdc-album2.jpg",
        "year": 2010,
        "price": 25,
        "discount": null,
        "description": "'Iron Man 2' es la banda sonora de la película de Marvel. Incluye clásicos de AC/DC como 'Shoot to Thrill' y 'Thunderstruck'.",
        "exclusive": 1,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Back in Black",
        "discography": "Discografía1",
        "image": "acdc-album3.webp",
        "year": 1980,
        "price": 25,
        "discount": null,
        "description": "'Back in Black' es el séptimo álbum de estudio de AC/DC y uno de los álbumes más vendidos de todos los tiempos. Incluye éxitos como 'You Shook Me All Night Long'.",
        "exclusive": 1,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Who Made Who",
        "discography": "Discografía1",
        "image": "acdc-album4.jfif",
        "year": 1986,
        "price": 25,
        "discount": null,
        "description": "'Who Made Who' es la banda sonora de la película de Stephen King, 'Maximum Overdrive'. Incluye canciones de AC/DC como 'Sink the Pink'.",
        "exclusive": 1,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "High Voltage",
        "discography": "Discografía1",
        "image": "acdc-album5.jpg",
        "year": 1976,
        "price": 25,
        "discount": null,
        "description": "'High Voltage' es el primer álbum internacional de AC/DC y presenta canciones como 'T.N.T.' y 'It's a Long Way to the Top (If You Wanna Rock 'n' Roll)'.",
        "exclusive": 1,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Power Up",
        "discography": "Discografía1",
        "image": "acdc-album6.jpg",
        "year": 2020,
        "price": 25,
        "discount": null,
        "description": "'Power Up' es el álbum más reciente de AC/DC, lanzado después de una pausa de seis años. Incluye canciones como 'Shot in the Dark' y 'Realize'.",
        "exclusive": 0,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Black Ice",
        "discography": "Discografía1",
        "image": "acdc-album7.jpg",
        "year": 2008,
        "price": 25,
        "discount": null,
        "description": "'Black Ice' es el decimoquinto álbum de estudio de AC/DC y marcó su regreso después de ocho años sin lanzar nuevos álbumes. Incluye canciones como 'Rock 'n' Roll Train'.",
        "exclusive": 1,
        "bandId": 1,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Use Your Illusion I",
        "discography": "Discografía1",
        "image": "guns-album1.jpg",
        "year": 1991,
        "price": 25,
        "discount": null,
        "description": "'Use Your Illusion I' es el tercer álbum de estudio de Guns N' Roses y contiene éxitos como 'November Rain' y 'Don't Cry'.",
        "exclusive": 1,
        "bandId": 2,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Chinese Democracy",
        "discography": "Discografía1",
        "image": "guns-album2.png",
        "year": 2008,
        "price": 25,
        "discount": null,
        "description": "'Chinese Democracy' es el quinto álbum de estudio de Guns N' Roses y marcó el regreso de la banda después de una larga pausa. Incluye canciones como 'Chinese Democracy' y 'Better'.",
        "exclusive": 0,
        "bandId": 2,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Spaghetti Incident?",
        "discography": "Discografía1",
        "image": "guns-album3.png",
        "year": 1993,
        "price": 25,
        "discount": null,
        "description": "'The Spaghetti Incident?' es el quinto álbum de estudio de Guns N' Roses y es una colección de versiones de canciones punk y rock. Incluye canciones como 'Since I Don't Have You' y 'Ain't It Fun'.",
        "exclusive": 0,
        "bandId": 2,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Nothing Lasts Forever",
        "discography": "Discografía1",
        "image": "guns-album4.png",
        "year": 2022,
        "price": 25,
        "discount": null,
        "description": "'Nothing Lasts Forever' es un álbum recopilatorio de Guns N' Roses que presenta una selección de sus canciones más icónicas. Incluye éxitos como 'Sweet Child o' Mine' y 'Welcome to the Jungle'.",
        "exclusive": 1,
        "bandId": 2,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Greatest Hits",
        "discography": "Discografía1",
        "image": "guns-album5.webp",
        "year": 2004,
        "price": 25,
        "discount": null,
        "description": "'Greatest Hits' es un álbum recopilatorio de Guns N' Roses que abarca los éxitos más grandes de la banda, incluyendo 'Sweet Child o' Mine' y 'Paradise City'.",
        "exclusive": 0,
        "bandId": 2,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Presence",
        "discography": "Discografía1",
        "image": "zeppelin-album1.png",
        "year": 1976,
        "price": 25,
        "discount": null,
        "description": "'Presence' es el séptimo álbum de estudio de Led Zeppelin y presenta canciones como 'Achilles' Last Stand' y 'Nobody's Fault but Mine'.",
        "exclusive": 0,
        "bandId": 3,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "In Through the Out Door",
        "discography": "Discografía1",
        "image": "zeppelin-album2.png",
        "year": 1979,
        "price": 25,
        "discount": null,
        "description": "'In Through the Out Door' es el octavo y último álbum de estudio de Led Zeppelin, con canciones como 'Fool in the Rain' y 'All My Love'.",
        "exclusive": 1,
        "bandId": 3,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Song Remains the Same",
        "discography": "Discografía1",
        "image": "zeppelin-album3.webp",
        "year": 1976,
        "price": 25,
        "discount": null,
        "description": "'The Song Remains the Same' es la banda sonora de la película homónima de Led Zeppelin y presenta actuaciones en vivo de la banda, incluyendo 'Stairway to Heaven' y 'Whole Lotta Love'.",
        "exclusive": 1,
        "bandId": 3,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "How the West Was Won",
        "discography": "Discografía1",
        "image": "zeppelin-album4.png",
        "year": 2003,
        "price": 25,
        "discount": null,
        "description": "'How the West Was Won' es un álbum en vivo de Led Zeppelin que documenta actuaciones en vivo de la banda en 1972. Incluye éxitos como 'Rock and Roll' y 'Dazed and Confused'.",
        "exclusive": 1,
        "bandId": 3,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Mothership",
        "discography": "Discografía1",
        "image": "zeppelin-album5.png",
        "year": 2007,
        "price": 25,
        "discount": null,
        "description": "'Mothership' es un álbum recopilatorio de Led Zeppelin que incluye algunas de sus mejores canciones, como 'Whole Lotta Love' y 'Immigrant Song'.",
        "exclusive": 1,
        "bandId": 3,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Absolution",
        "discography": "Discografía1",
        "image": "muse-album1.jpg",
        "year": 2003,
        "price": 25,
        "discount": null,
        "description": "'Absolution' es el tercer álbum de estudio de Muse y contiene canciones como 'Time Is Running Out' y 'Hysteria'.",
        "exclusive": 0,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Origin of Symmetry",
        "discography": "Discografía1",
        "image": "muse-album2.jpg",
        "year": 2001,
        "price": 25,
        "discount": null,
        "description": "'Origin of Symmetry' es el segundo álbum de estudio de Muse y presenta canciones como 'New Born' y 'Bliss'.",
        "exclusive": 1,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Showbiz",
        "discography": "Discografía1",
        "image": "muse-album3.jpg",
        "year": 1999,
        "price": 25,
        "discount": null,
        "description": "'Showbiz' es el álbum debut de Muse e incluye canciones como 'Sunburn' y 'Muscle Museum'.",
        "exclusive": 0,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Black Holes and Revelations",
        "discography": "Discografía1",
        "image": "muse-album4.jpg",
        "year": 2006,
        "price": 25,
        "discount": null,
        "description": "'Black Holes and Revelations' es el cuarto álbum de estudio de Muse y contiene canciones como 'Starlight' y 'Supermassive Black Hole'.",
        "exclusive": 1,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Resistance",
        "discography": "Discografía1",
        "image": "muse-album5.jpg",
        "year": 2009,
        "price": 25,
        "discount": null,
        "description": "'The Resistance' es el quinto álbum de estudio de Muse y presenta canciones como 'Uprising' y 'Undisclosed Desires'.",
        "exclusive": 1,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Drones",
        "discography": "Discografía1",
        "image": "muse-album6.jpg",
        "year": 2015,
        "price": 25,
        "discount": null,
        "description": "'Drones' es el séptimo álbum de estudio de Muse y presenta canciones como 'Dead Inside' y 'Psycho'.",
        "exclusive": 1,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Simulation Theory",
        "discography": "Discografía1",
        "image": "muse-album7.jfif",
        "year": 2018,
        "price": 25,
        "discount": null,
        "description": "'Simulation Theory' es el octavo álbum de estudio de Muse y presenta canciones como 'Pressure' y 'Thought Contagion'.",
        "exclusive": 1,
        "bandId": 4,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Nevermind",
        "discography": "Discografía1",
        "image": "nirvana-album1.webp",
        "year": 1991,
        "price": 25,
        "discount": null,
        "description": "'Nevermind' es el segundo álbum de estudio de Nirvana y contiene canciones icónicas como 'Smells Like Teen Spirit' y 'Come as You Are'.",
        "exclusive": 1,
        "bandId": 5,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "In Utero",
        "discography": "Discografía1",
        "image": "nirvana-album2.png",
        "year": 1993,
        "price": 25,
        "discount": null,
        "description": "'In Utero' es el tercer álbum de estudio de Nirvana y presenta canciones como 'Heart-Shaped Box' y 'Rape Me'.",
        "exclusive": 0,
        "bandId": 5,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Bleach",
        "discography": "Discografía1",
        "image": "nirvana-album3.webp",
        "year": 1989,
        "price": 25,
        "discount": null,
        "description": "'Bleach' es el álbum debut de Nirvana y contiene canciones como 'About a Girl' y 'Blew'.",
        "exclusive": 1,
        "bandId": 5,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Live at Reading",
        "discography": "Discografía1",
        "image": "nirvana-album4.jpg",
        "year": 2009,
        "price": 25,
        "discount": null,
        "description": "'Live at Reading' es un álbum en vivo que documenta la histórica actuación de Nirvana en el Festival de Reading en 1992. Incluye éxitos como 'Lithium' y 'All Apologies'.",
        "exclusive": 1,
        "bandId": 5,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Wall",
        "discography": "Discografía1",
        "image": "pinkFloyd-album1.jpg",
        "year": 1979,
        "price": 25,
        "discount": null,
        "description": "'The Wall' es el undécimo álbum de estudio de Pink Floyd y es un álbum conceptual que incluye canciones icónicas como 'Comfortably Numb' y 'Another Brick in the Wall'.",
        "exclusive": 1,
        "bandId": 6,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Dark Side of the Moon",
        "discography": "Discografía1",
        "image": "pinkFloyd-album2.jpg",
        "year": 1973,
        "price": 25,
        "discount": null,
        "description": "'The Dark Side of the Moon' es uno de los álbumes más emblemáticos de Pink Floyd y contiene canciones como 'Money' y 'Time'.",
        "exclusive": 0,
        "bandId": 6,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Wish You Were Here",
        "discography": "Discografía1",
        "image": "pinkFloyd-album3.png",
        "year": 1975,
        "price": 25,
        "discount": null,
        "description": "'Wish You Were Here' es el noveno álbum de estudio de Pink Floyd y presenta canciones como 'Shine On You Crazy Diamond' y 'Wish You Were Here'.",
        "exclusive": 1,
        "bandId": 6,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Pulse",
        "discography": "Discografía1",
        "image": "pinkFloyd-album4.png",
        "year": 1995,
        "price": 25,
        "discount": null,
        "description": "'Pulse' es un álbum en vivo de Pink Floyd que documenta una de sus actuaciones en el Earls Court de Londres. Incluye éxitos como 'Comfortably Numb' y 'Run Like Hell'.",
        "exclusive": 1,
        "bandId": 6,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Division Bell",
        "discography": "Discografía1",
        "image": "pinkFloyd-album5.jpg",
        "year": 1994,
        "price": 25,
        "discount": null,
        "description": "'The Division Bell' es el catorceavo álbum de estudio de Pink Floyd y contiene canciones como 'High Hopes' y 'Keep Talking'.",
        "exclusive": 1,
        "bandId": 6,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Queen",
        "discography": "Discografía1",
        "image": "queen-album1.jpg",
        "year": 1973,
        "price": 25,
        "discount": null,
        "description": "El álbum homónimo de Queen, lanzado en 1973, marcó el comienzo de la carrera de la banda y presenta canciones como 'Keep Yourself Alive' y 'Liar'.",
        "exclusive": 0,
        "bandId": 7,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Queen II",
        "discography": "Discografía1",
        "image": "queen-album2.webp",
        "year": 1974,
        "price": 25,
        "discount": null,
        "description": "'Queen II', lanzado en 1974, es el segundo álbum de Queen y presenta canciones como 'Seven Seas of Rhye' y 'White Queen (As It Began)'.",
        "exclusive": 1,
        "bandId": 7,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "A Night at the Opera",
        "discography": "Discografía1",
        "image": "queen-album3.jpg",
        "year": 1975,
        "price": 25,
        "discount": null,
        "description": "'A Night at the Opera' es uno de los álbumes más icónicos de Queen y presenta la legendaria 'Bohemian Rhapsody', así como 'You're My Best Friend' y 'Love of My Life'.",
        "exclusive": 1,
        "bandId": 7,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "A Kind of Magic",
        "discography": "Discografía1",
        "image": "queen-album4.png",
        "year": 1986,
        "price": 25,
        "discount": null,
        "description": "'A Kind of Magic' es el decimocuarto álbum de estudio de Queen y presenta canciones como 'A Kind of Magic' y 'One Vision'.",
        "exclusive": 1,
        "bandId": 7,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Made in Heaven",
        "discography": "Discografía1",
        "image": "queen-album5.webp",
        "year": 1995,
        "price": 25,
        "discount": null,
        "description": "'Made in Heaven' es el decimoquinto y último álbum de estudio de Queen, lanzado después de la muerte de Freddie Mercury, y contiene canciones como 'Made in Heaven' y 'Too Much Love Will Kill You'.",
        "exclusive": 1,
        "bandId": 7,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "News of the World",
        "discography": "Discografía1",
        "image": "queen-album6.png",
        "year": 1977,
        "price": 25,
        "discount": null,
        "description": "'News of the World' es el sexto álbum de estudio de Queen y presenta canciones como 'We Will Rock You' y 'We Are the Champions'.",
        "exclusive": 0,
        "bandId": 7,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Evil Empire",
        "discography": "Discografía1",
        "image": "ratm-album1.jpg",
        "year": 1996,
        "price": 25,
        "discount": null,
        "description": "'Evil Empire' es el segundo álbum de estudio de Rage Against the Machine y presenta canciones como 'Bulls on Parade' y 'People of the Sun'.",
        "exclusive": 1,
        "bandId": 8,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Renegades",
        "discography": "Discografía1",
        "image": "ratm-album2.jpg",
        "year": 2000,
        "price": 25,
        "discount": null,
        "description": "'Renegades' es un álbum de versiones de Rage Against the Machine que incluye canciones reinterpretadas de artistas como Bruce Springsteen y The Rolling Stones.",
        "exclusive": 1,
        "bandId": 8,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Battle of Los Angeles",
        "discography": "Discografía1",
        "image": "ratm-album3.png",
        "year": 1999,
        "price": 25,
        "discount": null,
        "description": "'The Battle of Los Angeles' es el tercer álbum de estudio de Rage Against the Machine y contiene canciones como 'Testify' y 'Guerilla Radio'.",
        "exclusive": 1,
        "bandId": 8,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Live & Rare",
        "discography": "Discografía1",
        "image": "ratm-album4.jpg",
        "year": 1998,
        "price": 25,
        "discount": null,
        "description": "'Live & Rare' es un álbum en vivo y de rarezas de Rage Against the Machine que incluye actuaciones en directo y grabaciones raras.",
        "exclusive": 1,
        "bandId": 8,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "People of the Sun",
        "discography": "Discografía1",
        "image": "ratm-album5.jpg",
        "year": 2000,
        "price": 25,
        "discount": null,
        "description": "'People of the Sun' es un álbum recopilatorio de Rage Against the Machine que incluye versiones en vivo y lados B de la banda.",
        "exclusive": 1,
        "bandId": 8,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Blood Sugar Sex Magik",
        "discography": "Discografía1",
        "image": "rhcp-album1.jpg",
        "year": 1991,
        "price": 25,
        "discount": 20,
        "description": "'Blood Sugar Sex Magik' es un álbum icónico de Red Hot Chili Peppers y contiene canciones como 'Give It Away' y 'Under the Bridge'.",
        "exclusive": 0,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "By the Way",
        "discography": "Discografía1",
        "image": "rhcp-album2.jpg",
        "year": 2002,
        "price": 25,
        "discount": 10,
        "description": "'By the Way' es el octavo álbum de estudio de Red Hot Chili Peppers y presenta canciones como 'By the Way' y 'Can't Stop'.",
        "exclusive": 1,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Californication",
        "discography": "Discografía1",
        "image": "rhcp-album3.jpg",
        "year": 1999,
        "price": 25,
        "discount": null,
        "description": "'Californication' es uno de los álbumes más emblemáticos de Red Hot Chili Peppers y contiene canciones como 'Californication' y 'Scar Tissue'.",
        "exclusive": 1,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Red Hot Chili Peppers",
        "discography": "Discografía1",
        "image": "rhcp-album4.jpg",
        "year": 1984,
        "price": 25,
        "discount": null,
        "description": "El álbum homónimo 'The Red Hot Chili Peppers' fue el debut de la banda y presenta canciones como 'Get Up and Jump' y 'True Men Don't Kill Coyotes'.",
        "exclusive": 1,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Mother's Milk",
        "discography": "Discografía1",
        "image": "rhcp-album5.jpg",
        "year": 1989,
        "price": 25,
        "discount": 20,
        "description": "'Mother's Milk' es el cuarto álbum de estudio de Red Hot Chili Peppers y contiene canciones como 'Higher Ground' y 'Knock Me Down'.",
        "exclusive": 1,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "One Hot Minute",
        "discography": "Discografía1",
        "image": "rhcp-album6.jpg",
        "year": 1995,
        "price": 25,
        "discount": 10,
        "description": "'One Hot Minute' es el quinto álbum de estudio de Red Hot Chili Peppers y presenta canciones como 'Aeroplane' y 'My Friends'.",
        "exclusive": 0,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Getaway",
        "discography": "Discografía1",
        "image": "rhcp-album7.jpg",
        "year": 2016,
        "price": 25,
        "discount": null,
        "description": "'The Getaway' es el undécimo álbum de estudio de Red Hot Chili Peppers y presenta canciones como 'Dark Necessities' y 'Go Robot'.",
        "exclusive": 1,
        "bandId": 9,
        "genreId": 2,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Abbey Road",
        "discography": "Discografía1",
        "image": "thebeatles-album1.png",
        "year": 1969,
        "price": 25,
        "discount": null,
        "description": "'Abbey Road' es uno de los álbumes más icónicos de The Beatles y contiene canciones como 'Come Together' y 'Here Comes the Sun'.",
        "exclusive": 1,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Revolver",
        "discography": "Discografía1",
        "image": "thebeatles-album2.jpg",
        "year": 1966,
        "price": 25,
        "discount": null,
        "description": "'Revolver' es otro álbum influyente de The Beatles y presenta canciones como 'Eleanor Rigby' y 'Yellow Submarine'.",
        "exclusive": 1,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "A Hard Day's Night",
        "discography": "Discografía1",
        "image": "thebeatles-album3.jpg",
        "year": 1964,
        "price": 25,
        "discount": null,
        "description": "'A Hard Day's Night' es el tercer álbum de estudio de The Beatles y contiene canciones como 'A Hard Day's Night' y 'Can't Buy Me Love'.",
        "exclusive": 1,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Rubber Soul",
        "discography": "Discografía1",
        "image": "thebeatles-album4.png",
        "year": 1965,
        "price": 25,
        "discount": null,
        "description": "'Rubber Soul' es un álbum seminal de The Beatles y presenta canciones como 'In My Life' y 'Norwegian Wood'.",
        "exclusive": 0,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Please Please Me",
        "discography": "Discografía1",
        "image": "thebeatles-album5.png",
        "year": 1963,
        "price": 25,
        "discount": null,
        "description": "'Please Please Me' es el álbum debut de The Beatles y contiene canciones como 'I Saw Her Standing There' y 'Twist and Shout'.",
        "exclusive": 1,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Help!",
        "discography": "Discografía1",
        "image": "thebeatles-album6.png",
        "year": 1965,
        "price": 25,
        "discount": null,
        "description": "'Help!' es el quinto álbum de estudio de The Beatles y contiene canciones como 'Help!' y 'Ticket to Ride'.",
        "exclusive": 1,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Let It Be",
        "discography": "Discografía1",
        "image": "thebeatles-album7.png",
        "year": 1970,
        "price": 25,
        "discount": null,
        "description": "'Let It Be' es el último álbum de estudio de The Beatles y contiene canciones como 'Let It Be' y 'The Long and Winding Road'.",
        "exclusive": 1,
        "bandId": 10,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Narigón del Siglo",
        "discography": "Discografía1",
        "image": "divididos-album1.jpg",
        "year": 2000,
        "price": 25,
        "discount": null,
        "description": "'Narigón del Siglo' es un álbum icónico de Divididos y contiene canciones como 'Sisters' y 'Spaghetti del Rock'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "La Era de la Boludez",
        "discography": "Discografía1",
        "image": "divididos-album2.webp",
        "year": 1989,
        "price": 25,
        "discount": null,
        "description": "'La Era de la Boludez' es el tercer álbum de estudio de Divididos y presenta canciones como 'Que Ves' y 'Cajita Musical'.",
        "exclusive": 0,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Vivo Aca",
        "discography": "Discografía1",
        "image": "divididos-album3.jpg",
        "year": 2002,
        "price": 25,
        "discount": null,
        "description": "'Vivo Aca' es un álbum en vivo de Divididos grabado en el Estadio Obras en 2000 y presenta una selección de sus éxitos en directo.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Acariciando lo Áspero",
        "discography": "Discografía1",
        "image": "divididos-album4.jpg",
        "year": 1991,
        "price": 25,
        "discount": null,
        "description": "'Acariciando lo Áspero' es el segundo álbum de estudio de Divididos y presenta canciones como 'Zapatillas' y 'El 38'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Audio y Agua",
        "discography": "Discografía1",
        "image": "divididos-album5.jpg",
        "year": 2004,
        "price": 25,
        "discount": null,
        "description": "'Audio y Agua' es un álbum de Divididos que presenta canciones como 'Villancicos' y 'Huelga de Amores'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Viveza Criolla",
        "discography": "Discografía1",
        "image": "divididos-album6.webp",
        "year": 1986,
        "price": 25,
        "discount": null,
        "description": "'Viveza Criolla' es el primer álbum de estudio de Divididos y contiene canciones como 'Flecha en la Cabeza' y 'Muro de los Lamentos'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Amapola del '66",
        "discography": "Discografía1",
        "image": "divididos-album7.webp",
        "year": 2000,
        "price": 25,
        "discount": null,
        "description": "'Amapola del '66' es un álbum de Divididos que presenta canciones como 'Rasputín/Hey Jude' y 'Que Ves'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "40 Dibujos en el Piso",
        "discography": "Discografía1",
        "image": "divididos-album8.jpg",
        "year": 2008,
        "price": 25,
        "discount": null,
        "description": "'40 Dibujos en el Piso' es un álbum recopilatorio de Divididos que presenta canciones de su carrera, incluyendo 'Sisters' y 'Spaghetti del Rock'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Haciendo Cosas Raras",
        "discography": "Discografía1",
        "image": "divididos-album9.jpg",
        "year": 1987,
        "price": 25,
        "discount": null,
        "description": "'Haciendo Cosas Raras' es un álbum de Divididos y presenta canciones como 'Ay, que Dios Boludo' y 'Hace lo que Quieras, No lo que Debas'.",
        "exclusive": 1,
        "bandId": 11,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Despedazado por Mil Partes",
        "discography": "Discografía1",
        "image": "larenga-album1.jpg",
        "year": 1996,
        "price": 25,
        "discount": null,
        "description": "'Despedazado por Mil Partes' es el segundo álbum de estudio de La Renga y presenta canciones como 'Veneno' y 'El Final es en Donde Parti'.",
        "exclusive": 1,
        "bandId": 12,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Detonador de Sueños",
        "discography": "Discografía1",
        "image": "larenga-album2.jpg",
        "year": 2003,
        "price": 25,
        "discount": null,
        "description": "'Detonador de Sueños' es el sexto álbum de estudio de La Renga y presenta canciones como 'La Razon Que Te Demora' y 'Detonador de Sueños'.",
        "exclusive": 1,
        "bandId": 12,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "La Esquina del Infinito",
        "discography": "Discografía1",
        "image": "larenga-album3.webp",
        "year": 1994,
        "price": 25,
        "discount": null,
        "description": "'La Esquina del Infinito' es el tercer álbum de estudio de La Renga y presenta canciones como 'Veneno' y 'El Final es en Donde Parti'.",
        "exclusive": 1,
        "bandId": 12,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Trueno tierra",
        "discography": "Discografía1",
        "image": "larenga-album4.jpg",
        "year": 2000,
        "price": 25,
        "discount": null,
        "description": "'Trueno tierra' es el quinto álbum de estudio de La Renga y presenta canciones como 'Panic Show' y 'La Razon Que Te Demora'.",
        "exclusive": 1,
        "bandId": 12,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Insoportablemente Vivo",
        "discography": "Discografía1",
        "image": "larenga-album5.jpg",
        "year": 2001,
        "price": 25,
        "discount": null,
        "description": "'Insoportablemente Vivo' es un álbum en vivo de La Renga grabado en el Estadio Obras en 2001 y presenta una selección de sus éxitos en directo.",
        "exclusive": 1,
        "bandId": 12,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Esquivando Charcos",
        "discography": "Discografía1",
        "image": "larenga-album6.jpg",
        "year": 1991,
        "price": 25,
        "discount": null,
        "description": "'Esquivando Charcos' es el álbum debut de La Renga y presenta canciones como 'Veneno' y 'La Balada del Diablo y La Muerte'.",
        "exclusive": 1,
        "bandId": 12,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Ritual",
        "discography": "Discografía1",
        "image": "lospiojos-album1.jpg",
        "year": 1992,
        "price": 25,
        "discount": null,
        "description": "'Ritual' es el álbum debut de Los Piojos y contiene canciones como 'A Veces' y 'Cautivos'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Civilización",
        "discography": "Discografía1",
        "image": "lospiojos-album2.webp",
        "year": 1996,
        "price": 25,
        "discount": null,
        "description": "'Civilización' es el tercer álbum de estudio de Los Piojos y presenta canciones como 'Ando Ganas' y 'Hoy Es Adiós'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Tercer Arco",
        "discography": "Discografía1",
        "image": "lospiojos-album3.webp",
        "year": 2002,
        "price": 25,
        "discount": null,
        "description": "'Tercer Arco' es el sexto álbum de estudio de Los Piojos y presenta canciones como 'Escapar' y 'Azul'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Azul",
        "discography": "Discografía1",
        "image": "lospiojos-album4.webp",
        "year": 1998,
        "price": 25,
        "discount": null,
        "description": "'Azul' es el cuarto álbum de estudio de Los Piojos y presenta canciones como 'Babilonia' y 'Maradó'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Máquina de Sangre",
        "discography": "Discografía1",
        "image": "lospiojos-album5.jpg",
        "year": 2007,
        "price": 25,
        "discount": null,
        "description": "'Máquina de Sangre' es el octavo álbum de estudio de Los Piojos y presenta canciones como 'Pacífico' y 'Desde Lejos No Se Ve'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Verde Paisaje del Infierno",
        "discography": "Discografía1",
        "image": "lospiojos-album6.jpg",
        "year": 2000,
        "price": 25,
        "discount": null,
        "description": "'Verde Paisaje del Infierno' es el quinto álbum de estudio de Los Piojos y presenta canciones como 'Cruel' y 'El Farolito'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Chactuchac",
        "discography": "Discografía1",
        "image": "lospiojos-album7.webp",
        "year": 1993,
        "price": 25,
        "discount": null,
        "description": "'Chactuchac' es el segundo álbum de estudio de Los Piojos y presenta canciones como 'Civi' y 'Ay Ay Ay'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Huracanes en Luna Plateada",
        "discography": "Discografía1",
        "image": "lospiojos-album8.jpg",
        "year": 1997,
        "price": 25,
        "discount": null,
        "description": "'Huracanes en Luna Plateada' es el quinto álbum de estudio de Los Piojos y presenta canciones como 'Arco' y 'Salvavidas'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Fantasmas Peleándole al Viento",
        "discography": "Discografía1",
        "image": "lospiojos-album9.jfif",
        "year": 1999,
        "price": 25,
        "discount": null,
        "description": "'Fantasmas Peleándole al Viento' es el cuarto álbum de estudio de Los Piojos y presenta canciones como 'Ando Ganas' y 'El Final es en Donde Parti'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Ay Ay Ay",
        "discography": "Discografía1",
        "image": "lospiojos-album10.webp",
        "year": 2004,
        "price": 25,
        "discount": null,
        "description": "'Ay Ay Ay' es el noveno álbum de estudio de Los Piojos y presenta canciones como 'Yira' y 'Ay Ay Ay'.",
        "exclusive": 1,
        "bandId": 13,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Signos",
        "discography": "Discografía1",
        "image": "sodastereo-album1.webp",
        "year": 1986,
        "price": 25,
        "discount": null,
        "description": "'Signos' es el tercer álbum de estudio de Soda Stereo y presenta canciones como 'Persiana Americana' y 'En el Borde'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Nada Personal",
        "discography": "Discografía1",
        "image": "sodastereo-album2.jpg",
        "year": 1985,
        "price": 25,
        "discount": null,
        "description": "'Nada Personal' es el segundo álbum de estudio de Soda Stereo y presenta canciones como 'Cuando Pase el Temblor' y 'Nada Personal'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Soda Stereo",
        "discography": "Discografía1",
        "image": "sodastereo-album3.jpg",
        "year": 1984,
        "price": 25,
        "discount": null,
        "description": "'Soda Stereo' es el álbum debut homónimo de la banda y presenta canciones como 'Sobredosis de TV' y 'Trátame Suavemente'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Dynamo",
        "discography": "Discografía1",
        "image": "sodastereo-album4.jpg",
        "year": 1992,
        "price": 25,
        "discount": null,
        "description": "'Dynamo' es el quinto álbum de estudio de Soda Stereo y presenta canciones como 'Primavera 0' y 'Luna Roja'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Canción Animal",
        "discography": "Discografía1",
        "image": "sodastereo-album5.jpg",
        "year": 1990,
        "price": 25,
        "discount": null,
        "description": "'Canción Animal' es el cuarto álbum de estudio de Soda Stereo y presenta canciones como 'De Música Ligera' y 'Un Millón de Años Luz'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Ruido Blanco",
        "discography": "Discografía1",
        "image": "sodastereo-album6.webp",
        "year": 1987,
        "price": 25,
        "discount": null,
        "description": "'Ruido Blanco' es el cuarto álbum de estudio de Soda Stereo y presenta canciones como 'En el Borde' y 'Cuando Pase el Temblor'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Sueño Stereo",
        "discography": "Discografía1",
        "image": "sodastereo-album7.jpg",
        "year": 1995,
        "price": 25,
        "discount": null,
        "description": "'Sueño Stereo' es el séptimo álbum de estudio de Soda Stereo y presenta canciones como 'Ella Usó Mi Cabeza Como un Revólver' y 'Zoom'.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Démagogos",
        "discography": "Discografía1",
        "image": "sodastereo-album8.jpg",
        "year": 2008,
        "price": 25,
        "discount": null,
        "description": "'Démagogos' es un álbum recopilatorio de Soda Stereo que presenta una selección de sus éxitos a lo largo de su carrera.",
        "exclusive": 1,
        "bandId": 14,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "After Chabón",
        "discography": "Discografía1",
        "image": "sumo-album1.jpg",
        "year": 1987,
        "price": 25,
        "discount": null,
        "description": "'After Chabón' es el primer álbum de estudio de Sumo y presenta canciones como 'Los Viejos Vinagres' y 'La Rubia Tarada'.",
        "exclusive": 1,
        "bandId": 15,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Divididos por la Felicidad",
        "discography": "Discografía1",
        "image": "sumo-album2.jpg",
        "year": 1985,
        "price": 25,
        "discount": null,
        "description": "'Divididos por la Felicidad' es el segundo álbum de estudio de Sumo y presenta canciones como 'No Tan Distintos' y 'Heroina'.",
        "exclusive": 1,
        "bandId": 15,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Llegando los Monos",
        "discography": "Discografía1",
        "image": "sumo-album3.jpg",
        "year": 1988,
        "price": 25,
        "discount": null,
        "description": "'Llegando los Monos' es el tercer álbum de estudio de Sumo y presenta canciones como 'Next Week' y 'La Noche se Viene'.",
        "exclusive": 1,
        "bandId": 15,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Corpiños en la Madrugada",
        "discography": "Discografía1",
        "image": "sumo-album4.jfif",
        "year": 1986,
        "price": 25,
        "discount": null,
        "description": "'Corpiños en la Madrugada' es el cuarto álbum de estudio de Sumo y presenta canciones como 'Mejor No Hablar de Ciertas Cosas' y 'Regtest'.",
        "exclusive": 1,
        "bandId": 15,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Fiebre",
        "discography": "Discografía1",
        "image": "sumo-album5.webp",
        "year": 1989,
        "price": 25,
        "discount": null,
        "description": "'Fiebre' es el quinto álbum de estudio de Sumo y presenta canciones como 'No Acabes' y 'Sweet & Sour'.",
        "exclusive": 1,
        "bandId": 15,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Obras Cumbres",
        "discography": "Discografía1",
        "image": "sumo-album6.jpg",
        "year": 1987,
        "price": 25,
        "discount": null,
        "description": "'Obras Cumbres' es una recopilación de éxitos de Sumo, que incluye canciones destacadas de su carrera.",
        "exclusive": 1,
        "bandId": 15,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Oktubre",
        "discography": "Discografía1",
        "image": "indio-album1.jpg",
        "year": 1986,
        "price": 25,
        "discount": null,
        "description": "'Oktubre' es el primer álbum de estudio de Indio Solari como solista y presenta canciones como 'To Beef or Not to Beef' y 'Esa Estrella Era Mi Lujo'.",
        "exclusive": 1,
        "bandId": 16,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "La Mosca y la Sopa",
        "discography": "Discografía1",
        "image": "indio-album2.jpg",
        "year": 1988,
        "price": 25,
        "discount": null,
        "description": "'La Mosca y la Sopa' es el segundo álbum de estudio de Indio Solari como solista y presenta canciones como 'Las Habladurías del Mundo' y 'La Piba del Block'.",
        "exclusive": 1,
        "bandId": 16,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Luzbelito",
        "discography": "Discografía1",
        "image": "indio-album3.webp",
        "year": 1996,
        "price": 25,
        "discount": null,
        "description": "'Luzbelito' es el tercer álbum de estudio de Indio Solari como solista y presenta canciones como 'Tatuaje' y 'Yo Caníbal'.",
        "exclusive": 1,
        "bandId": 16,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Lobo Suelto, Cordero Atado",
        "discography": "Discografía1",
        "image": "indio-album4.jpg",
        "year": 2005,
        "price": 25,
        "discount": null,
        "description": "'Lobo Suelto, Cordero Atado' es el cuarto álbum de estudio de Indio Solari como solista y presenta canciones como 'El León en el Espejo' y 'Las Bases Anatómicas del Mal'.",
        "exclusive": 1,
        "bandId": 16,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Momo Sampler",
        "discography": "Discografía1",
        "image": "indio-album5.webp",
        "year": 2000,
        "price": 25,
        "discount": 20,
        "description": "'Momo Sampler' es el quinto álbum de estudio de Indio Solari como solista y presenta canciones como 'Flight 956' y 'Pabellón Séptimo'.",
        "exclusive": 1,
        "bandId": 16,
        "genreId": 3,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Is This It",
        "discography": "Discografía1",
        "image": "thestrokes-album1.png",
        "year": 2001,
        "price": 25,
        "discount": null,
        "description": "'Is This It' es el álbum debut de The Strokes, conocido por canciones como 'Last Nite' y 'Someday'.",
        "exclusive": 1,
        "bandId": 17,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The New Abnormal",
        "discography": "Discografía1",
        "image": "thestrokes-album2.jpg",
        "year": 2020,
        "price": 25,
        "discount": null,
        "description": "'The New Abnormal' es uno de los álbumes más recientes de The Strokes, que incluye canciones como 'Bad Decisions' y 'At The Door'.",
        "exclusive": 1,
        "bandId": 17,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Room on Fire",
        "discography": "Discografía1",
        "image": "thestrokes-album3.jpg",
        "year": 2003,
        "price": 25,
        "discount": null,
        "description": "'Room on Fire' es el segundo álbum de estudio de The Strokes y presenta canciones como '12:51' y 'Reptilia'.",
        "exclusive": 1,
        "bandId": 17,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Angels",
        "discography": "Discografía1",
        "image": "thestrokes-album4.jpg",
        "year": 2013,
        "price": 25,
        "discount": 5,
        "description": "'Angels' es un álbum de The Strokes que incluye canciones como 'One Way Trigger' y 'All the Time'.",
        "exclusive": 1,
        "bandId": 17,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Comedown Machine",
        "discography": "Discografía1",
        "image": "thestrokes-album5.webp",
        "year": 2013,
        "price": 25,
        "discount": null,
        "description": "'Comedown Machine' es otro álbum de The Strokes, que incluye canciones como 'All the Time' y 'One Way Trigger'.",
        "exclusive": 1,
        "bandId": 17,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Future Present Past",
        "discography": "Discografía1",
        "image": "thestrokes-album6.jpg",
        "year": 2016,
        "price": 25,
        "discount": null,
        "description": "'Future Present Past' es un EP de The Strokes que incluye canciones como 'OBLIVIUS' y 'Drag Queen'.",
        "exclusive": 1,
        "bandId": 17,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "AM",
        "discography": "Discografía1",
        "image": "arcticmonkeys-album1.jpg",
        "year": 2013,
        "price": 25,
        "discount": null,
        "description": "'AM' es uno de los álbumes más destacados de Arctic Monkeys e incluye canciones como 'Do I Wanna Know?' y 'R U Mine?'.",
        "exclusive": 1,
        "bandId": 18,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Car",
        "discography": "Discografía1",
        "image": "arcticmonkeys-album2.webp",
        "year": 2005,
        "price": 25,
        "discount": null,
        "description": "'The Car' es un álbum en vivo de Arctic Monkeys, grabado en el Teatro Olympia de París.",
        "exclusive": 1,
        "bandId": 18,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Favourite Worst Nightmare",
        "discography": "Discografía1",
        "image": "arcticmonkeys-album3.webp",
        "year": 2007,
        "price": 25,
        "discount": null,
        "description": "'Favourite Worst Nightmare' es el segundo álbum de estudio de Arctic Monkeys y presenta canciones como '505' y 'Fluorescent Adolescent'.",
        "exclusive": 1,
        "bandId": 18,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Humbug",
        "discography": "Discografía1",
        "image": "arcticmonkeys-album4.jpg",
        "year": 2009,
        "price": 25,
        "discount": 10,
        "description": "'Humbug' es el tercer álbum de estudio de Arctic Monkeys y presenta canciones como 'Crying Lightning' y 'Cornerstone'.",
        "exclusive": 1,
        "bandId": 18,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Suck It and See",
        "discography": "Discografía1",
        "image": "arcticmonkeys-album5.webp",
        "year": 2011,
        "price": 25,
        "discount": null,
        "description": "'Suck It and See' es el cuarto álbum de estudio de Arctic Monkeys y presenta canciones como 'Don't Sit Down 'Cause I've Moved Your Chair' y 'She's Thunderstorms'.",
        "exclusive": 1,
        "bandId": 18,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Currents",
        "discography": "Discografía1",
        "image": "tameimpala-album1.jpg",
        "year": 2015,
        "price": 25,
        "discount": null,
        "description": "'Currents' es uno de los álbumes más destacados de Tame Impala, que incluye canciones como 'Let It Happen' y 'The Less I Know the Better'.",
        "exclusive": 1,
        "bandId": 19,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "The Slow Rush",
        "discography": "Discografía1",
        "image": "tameimpala-album2.jpg",
        "year": 2020,
        "price": 25,
        "discount": null,
        "description": "'The Slow Rush' es uno de los álbumes más recientes de Tame Impala, que incluye canciones como 'Borderline' y 'Breathe Deeper'.",
        "exclusive": 1,
        "bandId": 19,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Lonerism",
        "discography": "Discografía1",
        "image": "tameimpala-album3.jpg",
        "year": 2012,
        "price": 25,
        "discount": null,
        "description": "'Lonerism' es otro álbum destacado de Tame Impala, que incluye canciones como 'Feels Like We Only Go Backwards' y 'Elephant'.",
        "exclusive": 1,
        "bandId": 19,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      },
      {
        "title": "Innerspeaker",
        "discography": "Discografía1",
        "image": "tameimpala-album4.jpg",
        "year": 2010,
        "price": 25,
        "discount": 10,
        "description": "'Innerspeaker' es el álbum debut de Tame Impala, conocido por canciones como 'Solitude Is Bliss' y 'Lucidity'.",
        "exclusive": 1,
        "bandId": 19,
        "genreId": 1,
        "createdAt": new Date(),
        "updatedAt": new Date()
      }


    ], {});
  },


  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Albums', null, {});
  }
};