'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Merchs', [
      {
        name: 'Mochila AC/DC 1',
        price: 30,
        discount: null,
        image: 'acdc-backpack1.png',
        bandId: 1,
        typeId: 5,
        description: 'Esta mochila con el logo de AC/DC es perfecta para los fanáticos. Está confeccionada con material resistente y cómodo, ideal para llevar tus pertenencias con estilo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mochila AC/DC 2',
        price: 30,
        discount: null,
        image: 'acdc-backpack2.png',
        bandId: 1,
        typeId: 5,
        description: 'Si buscas una alternativa a la mochila principal de AC/DC, esta es una excelente opción. Fabricada con material duradero y diseño exclusivo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Cartas AC/DC',
        price: 10,
        discount: null,
        image: 'acdc-cards.png',
        bandId: 1,
        typeId: 10,
        description: 'Esta baraja de cartas con diseño de AC/DC es ideal para los amantes del juego. Las cartas están impresas en material de alta calidad y son perfectas para pasar el tiempo con amigos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza AC/DC 1',
        price: 15,
        discount: null,
        image: 'acdc-cup1.png',
        bandId: 1,
        typeId: 4,
        description: 'Disfruta de tus bebidas favoritas en esta taza con el logo de AC/DC. Hecha de cerámica de calidad, esta taza es resistente y elegante al mismo tiempo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema AC/DC 1',
        price: 5,
        discount: null,
        image: 'acdc-emblem1.png',
        bandId: 1,
        typeId: 8,
        description: 'Este emblema con el logo de AC/DC es perfecto para personalizar tu ropa o accesorios. Está hecho de metal de alta calidad y es resistente al desgaste.',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera AC/DC 1',
        price: 40,
        discount: null,
        image: 'acdc-hoodie1.png',
        bandId: 1,
        typeId: 7,
        description: 'Esta sudadera con diseño de AC/DC es una prenda de calidad superior. Está confeccionada con algodón suave y resistente para brindarte comodidad y estilo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera AC/DC 2',
        price: 40,
        discount: null,
        image: 'acdc-hoodie2.png',
        bandId: 1,
        typeId: 7,
        description: 'Si buscas otra opción de sudadera, esta es perfecta. Fabricada con materiales de alta calidad y diseño exclusivo de AC/DC para los amantes de la música.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Púa AC/DC',
        price: 2,
        discount: null,
        image: 'acdc-pick.png',
        bandId: 1,
        typeId: 9,
        description: 'Esta púa de guitarra con el logo de AC/DC está hecha de material resistente. Ideal para músicos y fans de la banda que buscan un sonido auténtico.',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster AC/DC 1',
        price: 12,
        discount: null,
        image: 'acdc-poster1.png',
        bandId: 1,
        typeId: 3,
        description: 'Decora tus paredes con este póster decorativo de AC/DC. Impreso en papel de alta calidad, es una adición imprescindible para cualquier espacio de fans.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta AC/DC 1',
        price: 20,
        discount: null,
        image: 'acdc-shirt1.png',
        bandId: 1,
        typeId: 1,
        description: 'Esta camiseta con diseño de AC/DC es una prenda esencial para cualquier fan. Hecha de algodón suave y duradero para brindarte comodidad y estilo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Medias Guns N\' Roses',
        price: 15,
        discount: null,
        image: 'guns-indumentary1.png',
        bandId: 2,
        typeId: 11,
        description: 'Medias de alta calidad con el logo de Guns N\' Roses. Hechas de algodón suave y duradero.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Campera de Cuero Guns N\' Roses',
        price: 120,
        discount: null,
        image: 'guns-indumentary2.png',
        bandId: 2,
        typeId: 2,
        description: 'Campera de cuero genuino con diseño exclusivo de Guns N\' Roses. Excelente calidad y durabilidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Chaqueta sin Mangas Guns N\' Roses',
        price: 45,
        discount: null,
        image: 'guns-indumentary3.png',
        bandId: 2,
        typeId: 11,
        description: 'Chaqueta sin mangas de alta calidad con el emblema de Guns N\' Roses. Comodidad y estilo en uno.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Gorra Guns N\' Roses',
        price: 20,
        discount: null,
        image: 'guns-indumentary4.png',
        bandId: 2,
        typeId: 11,
        description: 'Gorra de primera calidad con el logo icónico de Guns N\' Roses. Protege del sol con estilo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Figuritas Funko Pop de Guns N\' Roses',
        price: 25,
        discount: null,
        image: 'guns-merch1.png',
        bandId: 2,
        typeId: 10,
        description: 'Colecciona estas figuritas Funko Pop de Guns N\' Roses. Detalles precisos y material duradero.',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Rompecabezas Guns N\' Roses',
        price: 30,
        discount: null,
        image: 'guns-merch2.png',
        bandId: 2,
        typeId: 10,
        description: 'Arma este rompecabezas de alta calidad con una imagen emblemática de Guns N\' Roses. Divertido y desafiante.',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Led Zeppelin 1',
        price: 25,
        discount: null,
        image: 'zeppelin-shirt1.png',
        bandId: 3,
        typeId: 1,
        description: 'Esta camiseta de Led Zeppelin es una pieza esencial para los fanáticos de la banda. Hecha de algodón suave y con un diseño emblemático, es cómoda y elegante.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Led Zeppelin 2',
        price: 25,
        discount: null,
        image: 'zeppelin-shirt2.png',
        bandId: 3,
        typeId: 1,
        description: 'Otra opción de camiseta de Led Zeppelin para los amantes de la música. Fabricada con algodón de alta calidad y diseño único de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Led Zeppelin 1',
        price: 45,
        discount: null,
        image: 'zeppelin-hoodie1.png',
        bandId: 3,
        typeId: 7,
        description: 'Esta sudadera de Led Zeppelin es ideal para mantenerte abrigado y mostrar tu amor por la banda. Fabricada con material suave y resistente.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker Led Zeppelin',
        price: 3,
        discount: null,
        image: 'zeppelin-sticker1.png',
        bandId: 3,
        typeId: 6,
        description: 'Este sticker de Led Zeppelin presenta el famoso "blimp" de la banda. Es resistente al agua y perfecto para decorar tus pertenencias.',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster de Conciertos de Led Zeppelin',
        price: 15,
        discount: null,
        image: 'zeppelin-poster1.png',
        bandId: 3,
        typeId: 3,
        description: 'Decora tus paredes con este póster que muestra imágenes de icónicos conciertos de Led Zeppelin. Impreso en papel de alta calidad para un aspecto impresionante.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster de Mothership de Led Zeppelin',
        price: 15,
        discount: null,
        image: 'zeppelin-poster2.png',
        bandId: 3,
        typeId: 3,
        description: 'Este póster presenta la portada del álbum "Mothership" de Led Zeppelin. Impreso en papel de alta calidad, es un imprescindible para los fans.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Muse 1 (Negra)',
        price: 50,
        discount: null,
        image: 'muse-hoodie1.png',
        bandId: 4,
        typeId: 7,
        description: 'Esta sudadera negra de Muse es perfecta para mantenerte abrigado con estilo. Fabricada con material de alta calidad, es cómoda y duradera.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza Muse 1 (Holes and Revelations)',
        price: 12,
        discount: null,
        image: 'muse-cup1.png',
        bandId: 4,
        typeId: 4,
        description: 'Disfruta de tus bebidas favoritas en esta taza de Muse con el arte del álbum "Holes and Revelations". Hecha de cerámica de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Muse 1 (Negra, Simple)',
        price: 20,
        discount: null,
        image: 'muse-shirt1.png',
        bandId: 4,
        typeId: 1,
        description: 'Esta camiseta negra simple de Muse es esencial para los fanáticos de la banda. Hecha de algodón suave y de calidad para brindarte comodidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Gorra Muse (Indumentaria)',
        price: 15,
        discount: null,
        image: 'muse-indumentary1.png',
        bandId: 4,
        typeId: 11,
        description: 'Completa tu look con esta gorra de Muse. Fabricada con material resistente, es un accesorio de calidad que muestra tu amor por la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Muse (Logo)',
        price: 5,
        discount: null,
        image: 'muse-emblem1.png',
        bandId: 4,
        typeId: 8,
        description: 'Decora tus pertenencias con este emblema con el logo de Muse. Hecho de material duradero y resistente al desgaste.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Muse 2 (Negra, Diseño Complejo)',
        price: 25,
        discount: null,
        image: 'muse-shirt2.png',
        bandId: 4,
        typeId: 1,
        description: 'Esta camiseta negra de Muse presenta un diseño más complejo para los amantes de la moda. Fabricada con algodón suave y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Nirvana 1',
        price: 50,
        discount: null,
        image: 'nirvana-hoodie1.png',
        bandId: 5,
        typeId: 7,
        description: 'Mantente abrigado con estilo con esta sudadera de Nirvana. Fabricada con material de alta calidad para comodidad y durabilidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Nirvana 1 (Fondo Negro)',
        price: 20,
        discount: null,
        image: 'nirvana-shirt1.png',
        bandId: 5,
        typeId: 1,
        description: 'Esta camiseta de Nirvana presenta un fondo negro con letra y logo en degradado amarillo/verde. Fabricada con algodón suave y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Nirvana 2 (Fondo Azul)',
        price: 20,
        discount: null,
        image: 'nirvana-shirt2.png',
        bandId: 5,
        typeId: 1,
        description: 'Lleva a tus héroes contigo con esta camiseta de Nirvana. Fondo azul y diseño amarillo con los miembros de la banda. Hecha de algodón suave y resistente.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Nirvana 1 (Carita)',
        price: 5,
        discount: null,
        image: 'nirvana-emblem1.png',
        bandId: 5,
        typeId: 8,
        description: 'Decora tus pertenencias con este emblema con el icónico logo de la carita de Nirvana. Hecho de material resistente.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Nirvana 2 (Carita en 4 Colores)',
        price: 6,
        discount: null,
        image: 'nirvana-emblem2.png',
        bandId: 5,
        typeId: 8,
        description: 'Lleva la carita de Nirvana en cuatro colores diferentes. Hechos de material duradero y resistentes al desgaste.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker Nirvana 1 (Álbumes)',
        price: 4,
        discount: null,
        image: 'nirvana-sticker1.png',
        bandId: 5,
        typeId: 6,
        description: 'Decora tus pertenencias con estos stickers que representan los icónicos álbumes de Nirvana. Resistentes al agua y duraderos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster Nirvana 1 (Colorido)',
        price: 10,
        discount: null,
        image: 'nirvana-poster1.png',
        bandId: 5,
        typeId: 3,
        description: 'Este póster colorido muestra a los miembros de Nirvana en un contraste oscuro con colores vibrantes en formas geométricas. Un elemento esencial para cualquier fan.',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Pink Floyd 1 (Triángulo Arcoíris, Negra)',
        price: 25,
        discount: null,
        image: 'floyd-shirt1.png',
        bandId: 6,
        typeId: 1,
        description: 'Esta camiseta negra de Pink Floyd presenta la distintiva imagen del triángulo con los colores del arcoíris. Hecha de algodón suave y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Pink Floyd 1 (Triángulo Arcoíris, Negra)',
        price: 55,
        discount: null,
        image: 'floyd-hoodie1.png',
        bandId: 6,
        typeId: 7,
        description: 'Mantente abrigado y muestra tu amor por Pink Floyd con esta sudadera negra. Presenta la icónica imagen del triángulo con los colores del arcoíris. Fabricada con material de alta calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Pink Floyd 2 (Animals, Blanca)',
        price: 30,
        discount: null,
        image: 'floyd-shirt2.png',
        bandId: 6,
        typeId: 1,
        description: 'Esta camiseta blanca de Pink Floyd presenta el álbum "Animals" con colores rosas pastel. Fabricada con algodón suave y de calidad para un look elegante.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Pink Floyd 1 (Cartas)',
        price: 10,
        discount: null,
        image: 'floyd-merch1.png',
        bandId: 6,
        typeId: 10,
        description: 'Este merchandising de Pink Floyd incluye una baraja de cartas temática de la banda. Ideal para los fanáticos. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster Pink Floyd 1 (All Seeing Eyes)',
        price: 15,
        discount: null,
        image: 'floyd-poster1.png',
        bandId: 6,
        typeId: 3,
        description: 'Decora tus paredes con este póster que presenta los "All Seeing Eyes" en colores suaves pasteles. Un elemento esencial para cualquier fan de Pink Floyd.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Pink Floyd 2 (Drinking Flask)',
        price: 20,
        discount: null,
        image: 'floyd-merch2.png',
        bandId: 6,
        typeId: 10,
        description: 'Este merchandising de Pink Floyd incluye una drinking flask de bolsillo con la imagen del triángulo y el arcoíris. Ideal para llevar tus bebidas con estilo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Pink Floyd 1 (Logos de Álbumes)',
        price: 5,
        discount: null,
        image: 'floyd-emblem1.png',
        bandId: 6,
        typeId: 8,
        description: 'Decora tus pertenencias con estos emblemas que presentan los logos de los álbumes de Pink Floyd. Hechos de material resistente y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Queen 1 (Negra)',
        price: 50,
        discount: null,
        image: 'queen-hoodie1.png',
        bandId: 7,
        typeId: 7,
        description: 'Muestra tu amor por Queen con esta sudadera negra con el icónico logo de la banda en amarillo. Fabricada con material de alta calidad para comodidad y estilo.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Queen 1 (Almohada Negra)',
        price: 20,
        discount: null,
        image: 'queen-merch1.png',
        bandId: 7,
        typeId: 10,
        description: 'Decora tu espacio con esta almohada negra que presenta a los integrantes de Queen. Un elemento esencial para cualquier fan de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Queen 1 (Blanca, Vintage)',
        price: 30,
        discount: null,
        image: 'queen-shirt1.png',
        bandId: 7,
        typeId: 1,
        description: 'Esta camiseta blanca de Queen tiene un estilo vintage y presenta a los miembros jóvenes de la banda. Hecha de algodón de alta calidad para un look retro.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster Queen 1 (Bohemian Rhapsody)',
        price: 15,
        discount: null,
        image: 'queen-poster1.png',
        bandId: 7,
        typeId: 3,
        description: 'Decora tus paredes con este póster en fondo negro que presenta a los integrantes de Queen haciendo la icónica pose de la canción "Bohemian Rhapsody". Un elemento esencial para cualquier fan.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Campera Queen 1 (Azul Marino)',
        price: 60,
        discount: null,
        image: 'queen-jacket1.png',
        bandId: 7,
        typeId: 2,
        description: 'Completa tu look con esta campera azul marino de Queen que presenta el logo flameante de la banda en la espalda. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Queen 1 (Negro y Dorado)',
        price: 6,
        discount: null,
        image: 'queen-emblem1.png',
        bandId: 7,
        typeId: 8,
        description: 'Decora tus pertenencias con este emblema negro y dorado del icónico logo de Queen. Hecho de material resistente y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Rage Against the Machine 1 (Roja)',
        price: 25,
        discount: null,
        image: 'rageMachine-shirt1.png',
        bandId: 8,
        typeId: 1,
        description: 'Esta camiseta roja de Rage Against the Machine presenta a un mexicano con rifle y bandolera en el diseño. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Rage Against the Machine 2 (Gris)',
        price: 20,
        discount: null,
        image: 'rageMachine-shirt2.png',
        bandId: 8,
        typeId: 1,
        description: 'Esta camiseta gris de Rage Against the Machine presenta un esqueleto blanco cantando y las palabras "Who Laughs Last?" Hecha de algodón suave y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker Rage Against the Machine 1 (Negro)',
        price: 3,
        discount: null,
        image: 'rageMachine-sticker1.png',
        bandId: 8,
        typeId: 6,
        description: 'Decora tus pertenencias con este sticker de Rage Against the Machine que presenta el nombre de la banda y una estrella roja en el centro. Resistentes al agua y duraderos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Rage Against the Machine 1 (Dibujo de Mujer)',
        price: 5,
        discount: null,
        image: 'rageMachine-emblem1.png',
        bandId: 8,
        typeId: 8,
        description: 'Decora tus pertenencias con este emblema que presenta el dibujo de lo que parece ser una mujer usando una máscara. Borde negro, fondo rojo, y la mujer es amarilla. Hecho de material resistente.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Buzo Red Hot Chili Peppers 1 (Negro)',
        price: 60,
        discount: null,
        image: 'rhcp-buzo1.png',
        bandId: 9,
        typeId: 7,
        description: 'Mantente abrigado con estilo con este buzo negro de Red Hot Chili Peppers que presenta el logo de la banda en el medio. Fabricado con material de alta calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Red Hot Chili Peppers 1 (Correa Roja)',
        price: 10,
        discount: null,
        image: 'rhcp-merch1.png',
        bandId: 9,
        typeId: 10,
        description: 'Completa tu look con esta correa color rojo de Red Hot Chili Peppers que presenta el logo de la banda. Un accesorio esencial para los fanáticos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Indumentaria Red Hot Chili Peppers 1 (Gorra Blanca)',
        price: 15,
        discount: null,
        image: 'rhcp-indumentary1.png',
        bandId: 9,
        typeId: 10,
        description: 'Agrega un toque de estilo con esta gorra blanca de Red Hot Chili Peppers que presenta el logo de la banda en la parte delantera. Fabricada con material de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Red Hot Chili Peppers 2 (Funko Pop Anthony Kiedis)',
        price: 18,
        discount: null,
        image: 'rhcp-merch2.png',
        bandId: 9,
        typeId: 10,
        description: 'Agrega a tu colección este Funko Pop de Anthony Kiedis, el carismático líder de Red Hot Chili Peppers. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Red Hot Chili Peppers 1 (Blanca)',
        price: 20,
        discount: null,
        image: 'rhcp-remera1.png',
        bandId: 9,
        typeId: 1,
        description: 'Esta camiseta blanca de Red Hot Chili Peppers presenta el logo de la banda. Fabricada con algodón suave y de calidad para un look fresco.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza Red Hot Chili Peppers 1 (Blanca)',
        price: 12,
        discount: null,
        image: 'rhcp-taza1.png',
        bandId: 9,
        typeId: 4,
        description: 'Disfruta de tus bebidas en esta taza blanca de Red Hot Chili Peppers con el logo de la banda. Hecha de cerámica de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising The Beatles 1 (Cartas Yellow Submarine)',
        price: 12,
        discount: null,
        image: 'beatles-merch1.png',
        bandId: 10,
        typeId: 10,
        description: 'Este merchandising de The Beatles incluye una baraja de cartas temática de "Yellow Submarine". Ideal para los fanáticos de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta The Beatles 1 ("Magical Mystery Tour")',
        price: 25,
        discount: null,
        image: 'beatles-shirt1.png',
        bandId: 10,
        typeId: 1,
        description: 'Esta camiseta de The Beatles presenta "Magical Mystery Tour" en un diseño único. Hecha de algodón suave y de calidad para los amantes del misterio.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Indumentaria The Beatles 1 (Anteojos Rosas)',
        price: 8,
        discount: null,
        image: 'beatles-indumentary1.png',
        bandId: 10,
        typeId: 5,
        description: 'Agrega un toque de estilo con estos anteojos rosas de The Beatles. Un accesorio ideal para completar tu look.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising The Beatles 2 (Abrebotellas Amarillo Submarino)',
        price: 10,
        discount: null,
        image: 'beatles-merch2.png',
        bandId: 10,
        typeId: 10,
        description: 'Abre tus bebidas con estilo con este abrebotellas en forma de submarino amarillo, inspirado en The Beatles.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster The Beatles 1 ("All You Need Is Love")',
        price: 18,
        discount: null,
        image: 'beatles-poster1.png',
        bandId: 10,
        typeId: 3,
        description: 'Decora tus paredes con este póster negro con colores rosas que presenta el mensaje "All You Need Is Love". Un elemento esencial para cualquier fan de The Beatles.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mochila The Beatles 1 ("Lonely Hearts")',
        price: 30,
        discount: null,
        image: 'beatles-backpack1.png',
        bandId: 10,
        typeId: 5,
        description: 'Lleva tus cosas con estilo en esta mochila azul inspirada en "Sgt. Pepper\'s Lonely Hearts Club Band" de The Beatles.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta The Beatles 2 (Negra Simple)',
        price: 20,
        discount: null,
        image: 'beatles-shirt2.png',
        bandId: 10,
        typeId: 1,
        description: 'Esta camiseta negra simple de The Beatles presenta el nombre de la banda en blanco. Ideal para los amantes de la simplicidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising The Beatles 3 (Muñequitos "Bobbleheads")',
        price: 15,
        discount: null,
        image: 'beatles-merch3.png',
        bandId: 10,
        typeId: 10,
        description: 'Agrega a tu colección estos muñequitos "bobbleheads" de los miembros de The Beatles. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza Divididos 1 (Icono del Personaje Cayendo)',
        price: 12,
        discount: null,
        image: 'divididos-cup1.png',
        bandId: 11,
        typeId: 4,
        description: 'Disfruta de tus bebidas en esta taza blanca que presenta el icónico personaje cayendo en varias instancias de blanco y negro, inspirado en Divididos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Divididos 1 (Negra Simple)',
        price: 20,
        discount: null,
        image: 'divididos-shirt1.png',
        bandId: 11,
        typeId: 1,
        description: 'Esta camiseta negra simple de Divididos presenta el nombre de la banda en blanco. Perfecta para los fanáticos de la simplicidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Divididos 1 (Mate Negro)',
        price: 25,
        discount: null,
        image: 'divididos-merch1.png',
        bandId: 11,
        typeId: 10,
        description: 'Disfruta de tus mates con estilo con este mate negro de Divididos que presenta el logo de la banda en blanco. Ideal para los amantes del mate. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Divididos 2 (Verde Agua, Narigón)',
        price: 22,
        discount: null,
        image: 'divididos-shirt2.png',
        bandId: 11,
        typeId: 1,
        description: 'Esta camiseta de color verde agua de Divididos presenta el icónico narigón en el diseño. Hecha de algodón suave y de calidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker Divididos 1 (Fondo Negro)',
        price: 3,
        discount: null,
        image: 'divididos-sticker1.png',
        bandId: 11,
        typeId: 6,
        description: 'Decora tus pertenencias con este sticker de Divididos que presenta el nombre de la banda en letras blancas sobre fondo negro. Resistente al agua y duradero.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster Divididos 1 (Vintage)',
        price: 20,
        discount: null,
        image: 'divididos-poster1.png',
        bandId: 11,
        typeId: 3,
        description: 'Decora tus paredes con este póster vintage que presenta a los miembros de Divididos durante un concierto. Un elemento esencial para los fans de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza La Renga 1 (Emblemada de los Miembros)',
        price: 14,
        discount: null,
        image: 'renga-cup1.png',
        bandId: 12,
        typeId: 4,
        description: 'Disfruta de tus bebidas en esta taza blanca completamente emblemada con un dibujo en blanco y negro y rojo de los miembros de La Renga tocando. Perfecta para los seguidores de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema La Renga 1 (Logo con la Frase "A los Mismos de Siempre")',
        price: 6,
        discount: null,
        image: 'renga-emblem1.png',
        bandId: 12,
        typeId: 8,
        description: 'Decora tus pertenencias con este emblema de La Renga que presenta el logo de la banda con la frase "A los Mismos de Siempre". Hecho de material resistente.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta La Renga 1 (Negra, "Casilda 2 de Septiembre")',
        price: 25,
        discount: null,
        image: 'renga-shirt1.png',
        bandId: 12,
        typeId: 1,
        description: 'Esta camiseta negra de La Renga presenta en letras color oro viejo la frase "Casilda 2 de Septiembre". Ideal para los fanáticos de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera La Renga 1 (Rojo Vibrante, Logo de la Estrella)',
        price: 45,
        discount: null,
        image: 'renga-hoodie1.png',
        bandId: 12,
        typeId: 7,
        description: 'Mantente abrigado con estilo en esta sudadera roja vibrante de La Renga que presenta el logo de la estrella en blanco en el medio. Ideal para destacar.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising La Renga 1 (Llavero Redondo Blanco)',
        price: 5,
        discount: null,
        image: 'renga-merch1.png',
        bandId: 12,
        typeId: 10,
        description: 'Lleva contigo el espíritu de La Renga con este llavero redondo blanco que presenta el icónico nombre de la banda en rojo. La frase es icónica. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Los Piojos 1 (Roja, Portada del Álbum "Ay Ay Ay")',
        price: 22,
        discount: null,
        image: 'piojos-shirt1.png',
        bandId: 13,
        typeId: 1,
        description: 'Luce con orgullo esta camiseta roja que presenta la portada del álbum "Ay Ay Ay" de Los Piojos. Ideal para los fanáticos de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza Los Piojos 1 (Iconos Blanco y Negro)',
        price: 10,
        discount: null,
        image: 'piojos-cup1.png',
        bandId: 13,
        typeId: 4,
        description: 'Disfruta de tus bebidas en esta taza blanca que presenta múltiples iconos en blanco y negro de Los Piojos. Perfecta para los seguidores de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Los Piojos 1 (Llavero Blanco y Negro)',
        price: 5,
        discount: null,
        image: 'piojos-merch1.png',
        bandId: 13,
        typeId: 10,
        description: 'Lleva contigo el espíritu de Los Piojos con este llavero blanco y negro que presenta el icónico icono de la banda. Ideal para tus llaves u objetos personales.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Indumentaria Los Piojos 1 (Medias Rojas, Temática "Ay Ay Ay")',
        price: 8,
        discount: null,
        image: 'piojos-indumentary1.png',
        bandId: 13,
        typeId: 11,
        description: 'Viste tus pies con estas medias rojas temáticas del disco "Ay Ay Ay" de Los Piojos. Hechas de material de calidad para tu comodidad.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Indumentaria Soda Stereo 1 (Bufanda Negra con Iconos)',
        price: 18,
        discount: null,
        image: 'sodaStereo-indumentary1.png',
        bandId: 14,
        typeId: 11,
        description: 'Mantente abrigado con estilo con esta bufanda negra que presenta iconos de la banda en amarillo y detalles en blanco. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Soda Stereo 1 (Negra Simple, Icono de las 3 Personitas)',
        price: 20,
        discount: null,
        image: 'sodaStereo-shirt1.png',
        bandId: 14,
        typeId: 1,
        description: 'Esta camiseta negra simple de Soda Stereo presenta el icónico icono de las 3 personitas paradas una al lado de la otra. Ideal para los fans de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Soda Stereo 2 (Negra Simple, Icono en Blanco)',
        price: 20,
        discount: null,
        image: 'sodaStereo-shirt2.png',
        bandId: 14,
        typeId: 1,
        description: 'Esta camiseta negra simple de Soda Stereo presenta el icono en blanco de la flecha y los círculos remarcando el logo donde la "S" se comparte para "Soda" y "Stereo". Ideal para los amantes del diseño minimalista.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Soda Stereo 1 (Llavero Amarillo, Logo y Círculos)',
        price: 5,
        discount: null,
        image: 'sodaStereo-merch1.png',
        bandId: 14,
        typeId: 10,
        description: 'Lleva el espíritu de Soda Stereo contigo con este llavero amarillo que presenta el logo de la banda y los círculos característicos. Ideal para tus llaves u objetos personales.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza Soda Stereo 1 (Icono de "Música Ligera")',
        price: 12,
        discount: null,
        image: 'sodaStereo-cup1.png',
        bandId: 14,
        typeId: 4,
        description: 'Disfruta de tus bebidas en esta taza blanca que presenta el icono de "Música Ligera" en círculo. Perfecta para los seguidores de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Sumo 1 (Negra Simple, Nombre en Rojo)',
        price: 18,
        discount: null,
        image: 'sumo-shirt1.png',
        bandId: 15,
        typeId: 1,
        description: 'Esta camiseta negra simple de Sumo presenta el nombre de la banda en rojo. Ideal para los fans que aprecian la sencillez.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Sumo 1 (Negra, Nombre en Rojo)',
        price: 30,
        discount: null,
        image: 'sumo-hoodie1.png',
        bandId: 15,
        typeId: 7,
        description: 'Mantente abrigado con estilo en esta sudadera negra de Sumo que presenta el nombre de la banda en rojo. Perfecta para los días más frescos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Sumo 2 (Blanco y Negro, Cantante Principal)',
        price: 22,
        discount: null,
        image: 'sumo-shirt2.png',
        bandId: 15,
        typeId: 1,
        description: 'Lleva contigo la imagen del icónico cantante principal de Sumo con esta camiseta en blanco y negro. El nombre de la banda se encuentra por encima. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster Sumo 1 (Blanco y Negro, Cantante con Micrófono)',
        price: 15,
        discount: null,
        image: 'sumo-poster1.png',
        bandId: 15,
        typeId: 3,
        description: 'Decora tus paredes con este póster en blanco y negro del cantante de Sumo sosteniendo un micrófono y mirando hacia un costado. El nombre de la banda se destaca en rojo por encima.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Indio Solari 1 (Negro, Dibujo del Indio Cantando)',
        price: 25,
        discount: null,
        image: 'indioSolari-shirt1.png',
        bandId: 16,
        typeId: 1,
        description: 'Esta camiseta negra presenta un dibujo del Indio Solari cantando en color oro viejo. Ideal para los seguidores del icónico cantante.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Indio Solari 1 (Conservadora Redonda Negra)',
        price: 32,
        discount: null,
        image: 'indioSolari-merch1.png',
        bandId: 16,
        typeId: 10,
        description: 'Mantén tus bebidas frías con estilo en esta conservadora redonda negra que presenta la imagen del Indio Solari en blanco y negro. Perfecta para llevar en tus salidas.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Indumentaria Indio Solari 1 (Pantalón Negro con Imagen del Indio)',
        price: 40,
        discount: null,
        image: 'indioSolari-indumentary1.png',
        bandId: 16,
        typeId: 11,
        description: 'Viste con actitud este pantalón negro en el que una pierna tiene la imagen del Indio Solari en blanco y negro. Un toque distintivo para los fans.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster Indio Solari 1 (Concierto del Indio)',
        price: 18,
        discount: null,
        image: 'indioSolari-poster1.png',
        bandId: 16,
        typeId: 3,
        description: 'Decora tu espacio con este póster de un concierto del Indio Solari. La imagen destaca al cantante con el micrófono en una mano y el puño levantado en tonalidad aqua.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Taza Indio Solari 1 (Caricatura del Indio)',
        price: 12,
        discount: null,
        image: 'indioSolari-cup1.png',
        bandId: 16,
        typeId: 4,
        description: 'Disfruta de tus bebidas en esta taza que presenta una caricatura del Indio Solari. Ideal para los seguidores del artista.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising Indio Solari 2 (Set Completo de Mate Negro)',
        price: 55,
        discount: null,
        image: 'indioSolari-merch2.png',
        bandId: 16,
        typeId: 10,
        description: 'Este set completo de mate negro incluye todo lo que necesitas: azúcar, yerba, termo y una bolsa de cuero para llevarlos. Cada artículo presenta el logo del Indio y su imagen en blanco y negro. Exclusive: 0',
        exclusive: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta The Strokes 1 (Negra Manga Larga, Icono Circular)',
        price: 30,
        discount: null,
        image: 'strokes-shirt1.png',
        bandId: 17,
        typeId: 1,
        description: 'Luce con estilo esta camiseta negra de manga larga que presenta el icónico icono circular de la banda con su nombre. Perfecta para los fanáticos de The Strokes.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta The Strokes 2 (Vintage de los Miembros de la Banda)',
        price: 25,
        discount: null,
        image: 'strokes-shirt2.png',
        bandId: 17,
        typeId: 1,
        description: 'Esta camiseta vintage de The Strokes presenta una imagen de los miembros de la banda. Ideal para los amantes del estilo retro.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Póster The Strokes 1 ("New Abnormal")',
        price: 15,
        discount: null,
        image: 'strokes-poster1.png',
        bandId: 17,
        typeId: 3,
        description: 'Decora tus paredes con el póster "New Abnormal" de The Strokes. Una adición perfecta para los fanáticos de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker The Strokes 1 (Vintage, Fondo Celeste)',
        price: 5,
        discount: null,
        image: 'strokes-sticker1.png',
        bandId: 17,
        typeId: 6,
        description: 'Decora tus pertenencias con este sticker vintage de The Strokes. Presenta un fondo celeste con letras rojas y bordes negros del nombre de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Merchandising The Strokes 1 (Ropita para Perro con Logo Celeste Brillante)',
        price: 18,
        discount: null,
        image: 'strokes-merch1.png',
        bandId: 17,
        typeId: 10,
        description: 'Viste a tu perro con este adorable ropita que presenta el logo celeste brillante de The Strokes. ¡Tu mascota también puede ser un fan de la banda!',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Arctic Monkeys 1 (Negra, Nombre en Blanco)',
        price: 20,
        discount: null,
        image: 'arcticMonkeys-shirts1.png',
        bandId: 18,
        typeId: 1,
        description: 'Luce con estilo esta camiseta negra que presenta el nombre de la banda en blanco. Ideal para los fanáticos de Arctic Monkeys.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Arctic Monkeys 2 (Blanca, Nombre en Negro)',
        price: 20,
        discount: null,
        image: 'arcticMonkeys-shirts2.png',
        bandId: 18,
        typeId: 1,
        description: 'Esta remera blanca presenta el nombre de la banda en negro. Una opción simple y elegante para los seguidores de Arctic Monkeys.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Arctic Monkeys 1 (Negra, Nombre en Blanco)',
        price: 35,
        discount: null,
        image: 'arcticMonkeys-hoodie1.png',
        bandId: 18,
        typeId: 7,
        description: 'Mantente abrigado con estilo en esta sudadera negra de Arctic Monkeys que presenta el nombre de la banda en blanco. Perfecta para los días frescos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sudadera Arctic Monkeys 2 (Blanca, Nombre en Blanco)',
        price: 35,
        discount: null,
        image: 'arcticMonkeys-hoodie2.png',
        bandId: 18,
        typeId: 7,
        description: 'Esta sudadera blanca de Arctic Monkeys presenta el nombre de la banda en blanco. Una opción cómoda y sencilla para los amantes de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker Arctic Monkeys 1 (Estilo Artístico a Tinta)',
        price: 5,
        discount: null,
        image: 'arcticMonkeys-sticker1.png',
        bandId: 18,
        typeId: 6,
        description: 'Decora tus pertenencias con este sticker horizontal de Arctic Monkeys que presenta a los miembros de la banda y el nombre en blanco y negro en un estilo artístico a tinta.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Tame Impala 1 (Negra, Álbum "Currents")',
        price: 22,
        discount: null,
        image: 'tameImpala-shirt1.png',
        bandId: 19,
        typeId: 1,
        description: 'Lleva contigo el icónico álbum "Currents" de Tame Impala con esta camiseta negra. Perfecta para los fanáticos de la banda.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Camiseta Tame Impala 2 (Blanca, Logo Estilo Mandala)',
        price: 20,
        discount: null,
        image: 'tameImpala-shirt2.png',
        bandId: 19,
        typeId: 1,
        description: 'Esta camiseta blanca presenta un logo estilo "mandala" en el medio con colores psicodélicos oscuros. Ideal para los seguidores de Tame Impala.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sticker Tame Impala 1 (Cabeza de Costado con Colores Psicodélicos)',
        price: 4,
        discount: null,
        image: 'tameImpala-sticker1.png',
        bandId: 19,
        typeId: 6,
        description: 'Decora tus pertenencias con esta cabeza de costado con capas de colores psicodélicos desde violeta hasta amarillo. Un toque psicodélico para tus objetos.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Emblema Tame Impala 1 (Logo de la Banda en Círculo)',
        price: 5,
        discount: null,
        image: 'tameImpala-emblem1.png',
        bandId: 19,
        typeId: 8,
        description: 'Lleva el logo de Tame Impala en un círculo con letras blancas y sombra arcoíris. Ideal para personalizar tu ropa y accesorios.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mochila Tame Impala 1 (Arte Abstracto, Colorida)',
        price: 45,
        discount: null,
        image: 'tameImpala-backpack1.png',
        bandId: 19,
        typeId: 5,
        description: 'Lleva contigo el arte abstracto de Tame Impala con esta mochila colorida. Presenta una mano gigante hundiéndose en un océano colorido a punto de agarrar la luna.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Toca Discos Vintage',
        price: 60,
        discount: null,
        image: 'capsula1.jpg',
        bandId: null,
        typeId: 12,
        description: 'Viaja en el tiempo con este tocadiscos vintage de la Cápsula del Tiempo. Disfruta de la música en su forma más clásica y auténtica.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Walkman Retro',
        price: 30,
        discount: null,
        image: 'capsula2.jpg',
        bandId: null,
        typeId: 12,
        description: 'Revive la era de los walkman con este reproductor de cintas retro de la Cápsula del Tiempo. Perfecto para los amantes de la nostalgia musical.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Boombox Clásico',
        price: 50,
        discount: null,
        image: 'capsula3.jpg',
        bandId: null,
        typeId: 12,
        description: 'Lleva contigo la música a todas partes con este boombox clásico de la Cápsula del Tiempo. Disfruta de tus canciones favoritas con estilo retro.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Gramófono Antiguo',
        price: 70,
        discount: null,
        image: 'capsula4.jpg',
        bandId: null,
        typeId: 12,
        description: 'Sumérgete en la nostalgia musical con este gramófono antiguo de la Cápsula del Tiempo. Experimenta el encanto del sonido vintage.',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Air Guitars Coloridas',
        price: 12,
        discount: null,
        image: 'capsula5.jpg',
        bandId: null,
        typeId: 12,
        description: 'Agita la diversión en conciertos y eventos con estas air guitars coloridas de la Cápsula del Tiempo. ¡Siente la emoción de tocar como un rockstar sin preocuparte por las cuerdas!',
        exclusive: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },





    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Merchs', null, {});
  }
};